"""add project_id to keyword_rankings

Revision ID: 04bcc7c7bf70
Revises: 
Create Date: 2025-08-01 18:27:00.969351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04bcc7c7bf70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_scans_id'), table_name='keyword_scans')
    op.drop_table('keyword_scans')
    op.add_column('keyword_rankings', sa.Column('project_id', sa.Integer(), nullable=False))
    op.alter_column('keyword_rankings', 'keyword_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('keyword_rankings', 'search_engine',
               existing_type=postgresql.ENUM('GOOGLE', 'BING', 'YAHOO', name='searchengine'),
               nullable=False)
    op.alter_column('keyword_rankings', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('keyword_rankings', 'device',
               existing_type=postgresql.ENUM('DESKTOP', 'MOBILE', name='devicetype'),
               nullable=False)
    op.drop_constraint(op.f('keyword_rankings_keyword_id_fkey'), 'keyword_rankings', type_='foreignkey')
    op.create_foreign_key(None, 'keyword_rankings', 'keywords', ['keyword_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'keyword_rankings', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keyword_rankings', type_='foreignkey')
    op.drop_constraint(None, 'keyword_rankings', type_='foreignkey')
    op.create_foreign_key(op.f('keyword_rankings_keyword_id_fkey'), 'keyword_rankings', 'keywords', ['keyword_id'], ['id'])
    op.alter_column('keyword_rankings', 'device',
               existing_type=postgresql.ENUM('DESKTOP', 'MOBILE', name='devicetype'),
               nullable=True)
    op.alter_column('keyword_rankings', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('keyword_rankings', 'search_engine',
               existing_type=postgresql.ENUM('GOOGLE', 'BING', 'YAHOO', name='searchengine'),
               nullable=True)
    op.alter_column('keyword_rankings', 'keyword_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('keyword_rankings', 'project_id')
    op.create_table('keyword_scans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_engine', postgresql.ENUM('GOOGLE', 'BING', 'YAHOO', name='searchengine'), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device', postgresql.ENUM('DESKTOP', 'MOBILE', name='devicetype'), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('snippet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scanned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('keyword_scans_keyword_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('keyword_scans_pkey'))
    )
    op.create_index(op.f('ix_keyword_scans_id'), 'keyword_scans', ['id'], unique=False)
    # ### end Alembic commands ###
